/**
 * Call-count planning for a pipeline run.
 *
 * Pure arithmetic over the DAG + depth matrix — no providers. The UI's
 * pre-flight estimate ("depth matrix × the price table") and the tests' exact
 * call-count assertions both build on these resolvers.
 *
 * Call model per core stage: 4 generation-phase calls (gen-a/b/c + merger)
 * plus 8 calls per critique round (3 critics, improver, 3 judges,
 * reconciler) — `loopCallCount(rounds)` from roles.ts. The gate consumes at
 * least one round, at most the depth's cap, so min plans run 1 round and max
 * plans run `loopCap(depth)`.
 */

import { LOOP_STAGE_COUNT, STAGE_NODES, stageNode, type ExpansionDef, type StageId, type StageNode } from "./stages";
import { DEFAULT_DEPTH, LOOP_CAPS, depthMatrix, loopCap, type Depth } from "./depth";
import { GENERATION_PHASE_ROLES, ROUND_ROLES } from "./roles";

/** Localisation target languages (spec RunConfig). */
export type Language = "en" | "es" | "de" | "ja" | "hi";

export const LANGUAGES: readonly Language[] = ["en", "es", "de", "ja", "hi"];

/** Documents the localisation pass translates: the 26 core deliverables. */
export const LOCALISATION_DOCUMENT_COUNT = LOOP_STAGE_COUNT;

export interface PlanOptions {
  depth: Depth;
  /** Selected localisation languages; defaults to all five. */
  languages?: readonly Language[];
  /** Critique rounds consumed per stage; defaults to the depth's cap (max plan). */
  rounds?: number;
}

/** One enumerated provider call in a planned run. */
export interface PlannedCall {
  stageId: StageId;
  /** Role from the canonical vocabulary (roles.ts) or the stage's expansion role. */
  role: string;
  kind: "loop-generation" | "loop-round" | "expansion" | "pass" | "localisation" | "rerun";
}

export interface StageCallPlan {
  stageId: StageId;
  loopCalls: number;
  expansionCalls: number;
  passCalls: number;
  total: number;
}

export interface PlanResult {
  depth: Depth;
  rounds: number;
  languages: readonly Language[];
  perStage: StageCallPlan[];
  totals: { loopCalls: number; expansionCalls: number; passCalls: number; total: number };
}

/** Calls generated by one expansion fan-out for the given matrix and languages. */
function expansionCallCount(
  expansion: ExpansionDef,
  matrix: ReturnType<typeof depthMatrix>,
  languageCount: number,
  documents: number,
): number {
  if ("perDepth" in expansion) return matrix[expansion.perDepth];
  if ("perLanguage" in expansion) return languageCount;
  if ("perLanguageDocuments" in expansion) return documents * languageCount;
  // Fixed count; data-dependent fan-outs (audit resolutions) are excluded
  // from the static plan — their count is only known at runtime.
  return expansion.dataDependent ? 0 : (expansion.count ?? 1);
}

/** Static call count for one node at the given depth/rounds/languages. */
function stageCallPlan(node: StageNode, opts: { depth: Depth; languages: readonly Language[]; rounds: number }): StageCallPlan {
  const matrix = depthMatrix(opts.depth);
  let loopCalls = 0;
  let passCalls = 0;

  if (node.kind === "stage") {
    loopCalls = GENERATION_PHASE_ROLES.length + ROUND_ROLES.length * opts.rounds;
  } else {
    for (const call of node.passCalls) {
      if (call.dataDependent) continue;
      passCalls += call.count ?? 1;
    }
    // Stage 36 re-runs the 5 weakest stages through the full loop, then
    // re-runs passes 32–35 (audit pair calls, synthesis, ladder, meta-score).
    if (node.rerun) {
      loopCalls += node.rerun.weakStages * (GENERATION_PHASE_ROLES.length + ROUND_ROLES.length * opts.rounds);
      for (const passId of node.rerun.recheckedPasses) {
        const pass = stageNode(passId);
        if (pass.kind === "pass") {
          passCalls += pass.passCalls.reduce((sum, c) => sum + (c.dataDependent ? 0 : (c.count ?? 1)), 0);
        }
      }
    }
  }

  const expansionCalls = node.expansions.reduce(
    (sum, e) => sum + expansionCallCount(e, matrix, opts.languages.length, LOCALISATION_DOCUMENT_COUNT),
    0,
  );

  return { stageId: node.id, loopCalls, expansionCalls, passCalls, total: loopCalls + expansionCalls + passCalls };
}

/**
 * Full call-count plan: per-stage loop/expansion/pass split plus totals.
 * Pass `rounds: 1` for the minimum-round plan (every gate clears first try)
 * or omit for the maximum-round plan (every stage burns the depth's cap).
 */
export function planCallCounts(options: PlanOptions): PlanResult {
  const opts = {
    depth: options.depth,
    languages: options.languages ?? LANGUAGES,
    rounds: options.rounds ?? loopCap(options.depth),
  };
  const perStage = STAGE_NODES.map((node) => stageCallPlan(node, opts));
  const totals = perStage.reduce(
    (acc, s) => ({
      loopCalls: acc.loopCalls + s.loopCalls,
      expansionCalls: acc.expansionCalls + s.expansionCalls,
      passCalls: acc.passCalls + s.passCalls,
      total: acc.total + s.total,
    }),
    { loopCalls: 0, expansionCalls: 0, passCalls: 0, total: 0 },
  );
  return { depth: opts.depth, rounds: opts.rounds, languages: opts.languages, perStage, totals };
}

/** Enumerate every planned call — the offline dry run's call manifest. */
export function enumerateCalls(options: PlanOptions): PlannedCall[] {
  const opts = {
    depth: options.depth,
    languages: options.languages ?? LANGUAGES,
    rounds: options.rounds ?? loopCap(options.depth),
  };
  const matrix = depthMatrix(opts.depth);
  const calls: PlannedCall[] = [];

  for (const node of STAGE_NODES) {
    if (node.kind === "stage") {
      for (const role of GENERATION_PHASE_ROLES) calls.push({ stageId: node.id, role, kind: "loop-generation" });
      for (let round = 1; round <= opts.rounds; round++) {
        for (const role of ROUND_ROLES) calls.push({ stageId: node.id, role, kind: "loop-round" });
      }
    } else {
      for (const call of node.passCalls) {
        if (call.dataDependent) continue;
        for (let i = 0; i < (call.count ?? 1); i++) calls.push({ stageId: node.id, role: call.role, kind: "pass" });
      }
      if (node.rerun) {
        const weak = STAGE_NODES.filter((n) => n.kind === "stage").slice(-node.rerun.weakStages);
        // Static stand-in for the runtime selection: the real weak-stage set
        // comes from stage 35's meta-score; a plan only needs the count.
        for (let w = 0; w < weak.length; w++) {
          for (const role of GENERATION_PHASE_ROLES) {
            calls.push({ stageId: node.id, role, kind: "rerun" });
          }
          for (let round = 1; round <= opts.rounds; round++) {
            for (const role of ROUND_ROLES) calls.push({ stageId: node.id, role, kind: "rerun" });
          }
        }
        for (const passId of node.rerun.recheckedPasses) {
          const pass = stageNode(passId);
          if (pass.kind !== "pass") continue;
          for (const call of pass.passCalls) {
            if (call.dataDependent) continue;
            for (let i = 0; i < (call.count ?? 1); i++) {
              calls.push({ stageId: node.id, role: call.role, kind: "rerun" });
            }
          }
        }
      }
    }

    for (const expansion of node.expansions) {
      let count: number;
      if ("perDepth" in expansion) count = matrix[expansion.perDepth];
      else if ("perLanguage" in expansion) count = opts.languages.length;
      else if ("perLanguageDocuments" in expansion) count = LOCALISATION_DOCUMENT_COUNT * opts.languages.length;
      else count = expansion.dataDependent ? 0 : (expansion.count ?? 1);
      for (let i = 0; i < count; i++) {
        calls.push({
          stageId: node.id,
          role: expansion.role,
          kind:
            node.kind === "pass" && ("perLanguage" in expansion || "perLanguageDocuments" in expansion)
              ? "localisation"
              : "expansion",
        });
      }
    }
  }

  return calls;
}

/** Convenience: { min, max } total call estimates for a depth (all five languages). */
export function minMaxPlan(depth: Depth = DEFAULT_DEPTH, languages: readonly Language[] = LANGUAGES): { min: number; max: number } {
  const min = planCallCounts({ depth, languages, rounds: 1 }).totals.total;
  const max = planCallCounts({ depth, languages, rounds: LOOP_CAPS[depth] }).totals.total;
  return { min, max };
}
